# Generated by Django 2.1.7 on 2019-04-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='email',
            field=models.EmailField(max_length=125),
        ),
    ]
